In [2]:
#Session 1: Numpy operations & Broadcasting
#If increase all product prices by 10% , how we update 10,000 values instantly
import numpy as np
prices=np.array([100,200,300,400])
prices*1.10

array([110., 220., 330., 440.])

In [ ]:
#Broadcasting concept
arr=np.array([[10,20,30],
              [40,50,60]
              ])
arr+5

array([[15, 25, 35],
       [45, 55, 65]])

In [ ]:
# You want only Sales Department salaries from dataset.
# Connect to numpy slicing
# 1D Indexing
arr=np.array([10,20,30,40,50])
arr[2]   #np.int64(30)
arr[1:4] #array([20, 30, 40])

array([20, 30, 40])

In [ ]:
# 2D Slicing
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
matrix[0] #array([1, 2, 3])
matrix[:,1] # array([2, 5, 8])
matrix[1:,0:2]
# array([[4, 5],
#        [7, 8]])



array([[4, 5],
       [7, 8]])

In [ ]:
# Boolean Indexing
arr=np.array([10,20,30,40,50])
arr[arr>25]
#array([30, 40, 50])

array([30, 40, 50])

In [ ]:
# A retail store tracks daily sales of three products:
sales_day1=np.array([120,85,60]) # Product A, B, C
sales_day2=np.array([150,90,75])
Total_sales=sales_day1+sales_day2
Total_sales #array([270, 175, 135])
percentage_growth=(sales_day2-sales_day1)/sales_day1*100
percentage_growth #array([25.        ,  5.88235294, 25.        ])
# Which product has highest growth
highest_growth_index = np.argmax(percentage_growth)
highest_growth_index # np.int64(0)

np.int64(0)

In [ ]:
# Temperature readings (In Celsius) for 5 cities over 3 years
temps=np.array([[25,28,30],
                [22,24,26],
                [30,32,33],
                [27,29,31],
                [20,21,23]])
Fahrenite_temps=temps*9/5+32
Fahrenite_temps
# array([[77. , 82.4, 86. ],
#        [71.6, 75.2, 78.8],
#        [86. , 89.6, 91.4],
#        [80.6, 84.2, 87.8],
#        [68. , 69.8, 73.4]])
correction = np.array([1, -1, 0])
corrected_temps=Fahrenite_temps+correction
corrected_temps
# array([[78. , 81.4, 86. ],
#        [72.6, 74.2, 78.8],
#        [87. , 88.6, 91.4],
#        [81.6, 83.2, 87.8],
#        [69. , 68.8, 73.4]])


array([[78. , 81.4, 86. ],
       [72.6, 74.2, 78.8],
       [87. , 88.6, 91.4],
       [81.6, 83.2, 87.8],
       [69. , 68.8, 73.4]])

In [ ]:
# Healthcare Dataset(Indexing)
# Hospital records patient blood pressure reading
bp=np.array([[120,80],
             [135,85],
             [140,90],
             [110,70],
             [125,75]])
# Extract the Systolic values
systolic = bp[:, 0]
# : → Select all rows
# 0 → Select column 0 (Systolic)
systolic
high_bp_patients = bp[bp[:, 0] > 130]
high_bp_patients
# array([[135,  85],
#        [140,  90]])
bp[bp[:,1] < 80, 1] = 80
bp
# array([[120,  80],
#        [135,  85],
#        [140,  90],
#        [110,  80],
#        [125,  80]])

array([[120,  80],
       [135,  85],
       [140,  90],
       [110,  80],
       [125,  80]])

In [3]:
# Agriculture Yield(Broadcasting + Indexing)

yields = np.array([[2.5,3.0,1.8],
                   [2.8,3.2,2.0],
                   [3.1,2.9,2.2],
                   [2.6,3.1,1.9]])
yields

# Increase yields of the second region by [0.2, 0.3, 0.1]
yields[1] += np.array([0.2, 0.3, 0.1])
yields

# Multiply the last column (Crop C) by 1.1
yields[:, -1] *= 1.1
yields

# Which crop has the highest average yield?
yields.mean(axis=0)
yields

array([[2.5 , 3.  , 1.98],
       [3.  , 3.5 , 2.31],
       [3.1 , 2.9 , 2.42],
       [2.6 , 3.1 , 2.09]])

In [ ]:
# A school stores students scores in three subjects
scores = np.array([[85, 78, 92],
                   [88, 74, 90],
                   [70, 65, 80],
                   [95, 89, 96]])

# 1️⃣ Top two students (first two rows)
totals = scores.sum(axis=1)
top_two_students = scores[np.argsort(-totals)[:2]]
top_two_students

# 2️⃣ All Math scores (first column)
math_scores = scores[:, 0]
math_scores

# 3️⃣ Students who scored > 90 in Science (third column)
high_science_students = scores[:, 2] > 90 #array([ True, False, False,  True])
high_science_students = scores[high_science_students]
# array([[85, 78, 92],
#        [95, 89, 96]])
high_science_students


array([[85, 78, 92],
       [95, 89, 96]])

In [ ]:
# Scenario: Farm Crop Yield Analysis
# A farm tracks the yield (in kilograms) of three different crops — Wheat, Rice, and Corn — across four seasons (Spring, Summer, Autumn, Winter).
# The farm manager wants to analyze the data to make better decisions for next year.
# Tasks
# - Create a 2D array representing crop yields for 3 crops across 4 seasons.
# - Rows = crops
# - Columns = seasons
# - Increase all yields by 10% to account for improved irrigation.
# - Extract only Wheat’s yields (the first crop).
# - Find the average yield per crop across all seasons.
# - Identify yields greater than 500 kg (to see which crops/seasons performed exceptionally well).

yields=np.array([[300,500,600,400], #Wheat in 4 Season
         [300,400,500,800], # Rice in 4 season
         [900,400,500,800]]) # Corn in 4 Season
Increased_yields=yields*1.10
Increased_yields
# array([[330., 550., 660., 440.],
#        [330., 440., 550., 880.],
#        [990., 440., 550., 880.]])

wheat_yeilds=yields[0]
wheat_yeilds # array([300, 500, 600, 400])
yields.mean() # np.float64(533.3333333333334)
Yields_greater_than_500=yields[yields>500]
Yields_greater_than_500

array([600, 800, 900, 800])

In [ ]:
# Rows = Products (Gadgets, Tools, Machines)
# Columns = Quarters (Q1, Q2, Q3, Q4)

production = np.array([[450, 520, 480, 500],   # Gadgets
                       [600, 580, 620, 610],   # Tools
                       [700, 720, 690, 710]])  # Machines

# Increase all production by 5%
production = production * 1.05

# Extract Gadgets production (first row)
gadgets_production = production[0]

# Average production per product (row-wise mean)
average_per_product = production.mean(axis=1)

# Values greater than 500 units
above_500 = production[production > 500]

print("Updated Production:\n", production)
print("\nGadgets Production:\n", gadgets_production)
print("\nAverage Production per Product:\n", average_per_product)
print("\nProduction values > 500:\n", above_500)

Updated Production:
 [[472.5 546.  504.  525. ]
 [630.  609.  651.  640.5]
 [735.  756.  724.5 745.5]]

Gadgets Production:
 [472.5 546.  504.  525. ]

Average Production per Product:
 [511.875 632.625 740.25 ]

Production values > 500:
 [546.  504.  525.  630.  609.  651.  640.5 735.  756.  724.5 745.5]


In [ ]:
# 🔷 Why Do We Use Pandas?

# We use Pandas for data analysis and data manipulation, especially when working with real-world structured data like:

# CSV files
# Excel files
# Databases
# JSON data

# 1️⃣ Works with Tabular Data (Like Excel)

# Pandas uses:
# Series → 1D data
# DataFrame → 2D table (rows + columns)
# It looks like an Excel sheet, so it's easy to understand.

# 2️⃣ Easy Data Cleaning

# You can easily:

# Handle missing values
# Remove duplicates
# Rename columns
# Filter data
# Replace values

# 3️⃣ Powerful Data Filtering

# 4️⃣ Built-in Statistical Functions

# df.mean()
# df.sum()
# df.describe()

# 5️⃣ Read & Write Files Easily

# pd.read_csv("data.csv")
# pd.read_excel("file.xlsx")
# df.to_csv("output.csv")

# 🔁 NumPy vs Pandas (Simple Difference)
#      NumPy	                   Pandas
# Works with arrays       	Works with tables
# Faster for math	       Better for data analysis
# No column names         	Has column labels
# 👉 NumPy = numerical operations
# 👉 Pandas = real-world data handling

In [ ]:
# Pandas - Series & Dataframes

import pandas as pd

data={
    "Name":["Prince","Aryan","Shreya"],
    "Salary":["70000",'80000',"900000"]
}
df=pd.DataFrame(data)
print(df)
type(df["Salary"])

     Name  Salary
0  Prince   70000
1   Aryan   80000
2  Shreya  900000


pandas.core.series.Series

In [ ]:
import pandas as pd

# 1️⃣ Read CSV file
df = pd.read_csv("Sample_data_for_Pandas_Operation.csv")

# 2️⃣ Basic Information
print("First 5 Rows:\n", df.head())
print(df.describe())
df.info()

# 3️⃣ Fill Missing Values
df.fillna(0, inplace=True)

# 4️⃣ Filter Data (Region = North)
north_region = df[df["Region"] == "North"]
print(north_region)

# 5️⃣ Sort Data by Monthly_Sales (Descending)
sorted_df = df.sort_values("Monthly_Sales", ascending=False)
print("\nSorted by Monthly Sales:\n", sorted_df)

# 6️⃣ Group By Region and Sum of Monthly Sales
grouped_data = df.groupby("Region")["Monthly_Sales"].sum()
print("\nTotal Monthly Sales by Region:\n", grouped_data)

First 5 Rows:
    Employee_ID Department Region  Salary  Experience_Years  \
0         1001      Sales  North   45000                 2   
1         1002  Marketing  South   52000                 3   
2         1003      Sales   East   47000                 4   
3         1004         HR   West   40000                 1   
4         1005         IT  North   60000                 5   

   Performance_Rating  Monthly_Sales  
0                 4.0       120000.0  
1                 3.0        98000.0  
2                 5.0       150000.0  
3                 3.0            0.0  
4                 4.0            0.0  

Statistical Summary:
        Employee_ID        Salary  Experience_Years  Performance_Rating  \
count    15.000000     15.000000         15.000000           14.000000   
mean   1008.000000  49666.666667          3.200000            3.785714   
std       4.472136   7158.079019          1.373213            0.892582   
min    1001.000000  39000.000000          1.000000         

In [ ]:
# Scenario: Corporate Employee Performance Dashboard
# A company tracks quarterly performance scores of employees across different departments.
# The HR analytics team wants to analyze this dataset to identify top performers, departmental trends, and highlight exceptional scores.

# Dataset
# The dataset contains the following columns:
# - Employee: Name of the employee
# - Department: Department they belong to (Sales, HR, IT, Finance, etc.)
# - Quarter: The quarter in which the performance score was recorded (Q1, Q2, Q3, Q4)
# - Score: Performance score (numeric value)

# Tasks
# - Filtering (Core Corporate Skill)
# - Find employees with Score > 90 (exceptional performers).
# - Filter records for the Sales department only.
# - Sorting (Power Moment)
# - Sort employees by Score in descending order to rank performance.
# - Sort by Department first, then Score to see departmental rankings.
# - Grouping (Core Corporate Skill)
# - Group by Department and calculate the average score per department.
# - Group by Quarter and find the maximum score achieved in each quarter.

# Business Context
# - Filtering helps HR identify exceptional performers and focus on specific departments.
# - Sorting creates clear performance rankings, useful for promotions or recognition programs.
# - Grouping reveals departmental strengths and quarterly performance trends, guiding training and resource allocation.

import pandas as pd

# 1️⃣ Load Dataset
df = pd.read_csv("Dataset.csv")
df.head()
df.info()
df.describe()

# OUTPUT

# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 10 entries, 0 to 9
# Data columns (total 4 columns):
#  #   Column      Non-Null Count  Dtype
# ---  ------      --------------  -----
#  0   Employee    10 non-null     object
#  1   Department  10 non-null     object
#  2   Quarter     10 non-null     object
#  3   Score       10 non-null     int64
# dtypes: int64(1), object(3)
# memory usage: 452.0+ bytes
# Score
# count	10.000000
# mean	85.300000
# std	9.177872
# min	70.000000
# 25%	78.500000
# 50%	86.500000
# 75%	91.500000
# max	99.000000


# ==============================
# 🔎 FILTERING (Core Corporate Skill)
# ==============================

# Exceptional performers (Score > 90)
exceptional_performers = df[df["Score"] > 90]
print("\nExceptional Performers (Score > 90):\n", exceptional_performers)

# 	Employee	Department	Quarter	Score
# 2	John	IT	Q1	92
# 4	David	Sales	Q2	95
# 8	Neha	Sales	Q3	99


# Sales Department records only
sales_department = df[df["Department"] == "Sales"]
print("\nSales Department Records:\n", sales_department)

# 	Employee	Department	Quarter	Score
# 0	Amit	Sales	Q1	78
# 4	David	Sales	Q2	95
# 8	Neha	Sales	Q3	99


# ==============================
# 📊 SORTING (Power Moment)
# ==============================

# Sort by Score (Descending)
sorted_by_score = df.sort_values("Score", ascending=False)
print("\nEmployees Ranked by Score:\n", sorted_by_score)

# 	Employee	Department	Quarter	Score
# 6	Alex	IT	Q2	70
# 9	Karan	IT	Q3	76
# 0	Amit	Sales	Q1	78
# 5	Meera	HR	Q2	80
# 1	Priya	HR	Q1	85
# 3	Sara	Finance	Q1	88
# 7	Ravi	Finance	Q2	90
# 2	John	IT	Q1	92
# 4	David	Sales	Q2	95
# 8	Neha	Sales	Q3	99


# Sort by Department first, then Score (Descending)
dept_wise_ranking = df.sort_values(["Department", "Score"], ascending=[True, False])
print("\nDepartment-wise Ranking:\n", dept_wise_ranking)

# 	Employee	Department	Quarter	Score
# 7	Ravi	Finance	Q2	90
# 3	Sara	Finance	Q1	88
# 1	Priya	HR	Q1	85
# 5	Meera	HR	Q2	80
# 2	John	IT	Q1	92
# 9	Karan	IT	Q3	76
# 6	Alex	IT	Q2	70
# 8	Neha	Sales	Q3	99
# 4	David	Sales	Q2	95
# 0	Amit	Sales	Q1	78


# ==============================
# 📈 GROUPING (Core Corporate Skill)
# ==============================

# Average score per Department
avg_score_department = df.groupby("Department")["Score"].mean()
print("\nAverage Score per Department:\n", avg_score_department)

# Department
# Finance    89.000000
# HR         82.500000
# IT         79.333333
# Sales      90.666667
# Name: Score, dtype: float64

# Maximum score per Quarter
max_score_quarter = df.groupby("Quarter")["Score"].max()
print("\nMaximum Score per Quarter:\n", max_score_quarter)

# Quarter
# Q1    92
# Q2    95
# Q3    99
# Name: Score, dtype: int64

# 📌 Business Interpretation (Corporate Understanding)
# 🔹 Filtering

# Identifies top performers (Score > 90).
# Helps HR focus on Sales department performance separately.

# 🔹 Sorting

# Creates performance ranking (important for promotions & bonuses).
# Department-wise sorting shows internal competition & leaders.

# 🔹 Grouping

# Department average score → shows which department performs best overall.
# Quarterly maximum score → identifies peak performance periods.
